app:
  port: 8080
  page_size: 5
db:
  file_name: "test.db"
  dsn: "test_user:test_pass@tcp(127.0.0.1:3306)/lr_book?charset=utf8mb4&parseTime=True&loc=Local"
  mongo_uri: "mongodb://localhost:27017"
  mongo_db_name: "lr_book"
cache:
  address: localhost:6379
  password: test_pass
  db: 0
  timeout: 50